Sprint3_qa
Zimbleik/Sprint_3 pull request #1
Opened 2023-07-16 18:27 UTC by Zimbleik

2023-07-18 10:50 UTC, kadirovgm requested changes

2023-07-18 10:50 UTC, kadirovgm commented on locators.py
> +class TestLocators:
Нужно исправить: давай попроубем оптимизировать локаторы, сейчас некоторые кажутся не стабильными

2023-07-18 10:50 UTC, kadirovgm commented on conftest.py
> +def driver():
супер!

2023-07-18 10:50 UTC, kadirovgm commented on README.md
> +# Sprint_3
Можно лучше: в readme лучше добавить описание проекта, использованные библиотеки и зависимости, описание тестов

2023-07-18 10:50 UTC, kadirovgm commented on __pycache__/conftest.cpython-39-pytest-7.3.1.pyc
нужно исправить: эта папка не относится к проекту, его надо либо удалить либо поместить в файл гитигнора

2023-07-18 10:50 UTC, kadirovgm commented on tests/__pycache__/test_constructor.cpython-39-pytest-7.3.1.pyc
нужно исправить: эта папка не относится к проекту, его надо либо удалить либо поместить в файл гитигнора

2023-07-18 10:50 UTC, kadirovgm commented on tests/test_constructor.py
> +    # В конструкторе по умолчанию выбрана вкладка булок
можно лучше: моветую метод комментирования "докстринг", так код будет выглядеть лаконичнее, но а то, что оставляешь краткие комменты - супер!

2023-07-18 10:50 UTC, kadirovgm commented on tests/test_constructor.py
> +    unselected_tabs = driver.find_elements(*TestLocators.UNSELECTED_INGREDIENT_TABS)
нужно исправить: придерживаем принципа атомарности тестов: один тест-одна проверка, так что везде, где в тестах по два ассерта, давай убирать, либо делать два теста, либо убирать излишние

2023-07-18 10:50 UTC, kadirovgm commented on tests/test_go_to_account.py
> +    email = "Dmitry_simchuk_11_666@gmail.com"
Можно лучше: тестовые статичные данные лучше выносить в отдельный файл типа [data.py](http://data.py/) или [urls.py](http://urls.py/)
Это нужно для легкой поддержке проекта и переиспользовании тестовых данных, мы должны стремиться к тому, чтобы разделять код и тестовые данные, тем самым избегая повторений.

2023-07-18 10:50 UTC, kadirovgm commented on tests/test_go_to_account.py
> +    driver.find_element(*TestLocators.EMAIL_FIELD).send_keys(email)
можно лучше: шаги авторизации вынести как отдельную функцию или фикстуру, так как эти шаги будут повторяться во многих кейсах, с шагами по регитрации та же история

2023-07-18 10:50 UTC, kadirovgm commented on tests/test_go_to_constructor.py
> +    assert "https://stellarburgers.nomoreparties.site/" == driver.current_url
нужно исправить: два ассера, можно здесь через AND сделать один

2023-07-18 10:50 UTC, kadirovgm commented on tests/test_go_to_constructor.py
> +
можно лучше: лучше избавляться от повторений в коде, во многих тестах одни и те же строки

2023-07-18 10:50 UTC, kadirovgm commented on tests/test_login_page.py
> +    assert "https://stellarburgers.nomoreparties.site/" == driver.current_url
нужно исправить: как данный ассерт проверяет что авторизация успешна?

2023-07-18 10:50 UTC, kadirovgm commented on tests/test_login_page.py
> +    assert "https://stellarburgers.nomoreparties.site/" == driver.current_url
нужно исправить: как данный ассерт проверяет что авторизация успешна?

проверка того, что URL поменялся на <url> не гарантирует, что страница прогрузилась, поэтому стоит ориентироваться на какие-либо элементы страницы, чекать, что они появились и отображаются корректно

2023-07-18 10:50 UTC, kadirovgm commented on tests/test_login_page.py
> +    assert "https://stellarburgers.nomoreparties.site/" == driver.current_url
нужно исправить: то же самое

2023-07-18 10:50 UTC, kadirovgm commented on tests/test_login_page.py
> +    assert "https://stellarburgers.nomoreparties.site/" == driver.current_url
нужно исправить, то же самое

2023-07-19 23:45 UTC, Zimbleik commented on tests/test_login_page.py
> +    assert "https://stellarburgers.nomoreparties.site/" == driver.current_url
Он же ждет пока не появится кнопка "Оформить заказ", без нее можно считать что авторизация не успешна
Тест укажет что ошибка в 42 строчке если указать неверные данные для авторизации

2023-07-19 23:50 UTC, Zimbleik commented on locators.py
> +class TestLocators:
Подскажи на какие конкретно обратить внимание?

2023-07-21 14:21 UTC, kadirovgm requested changes

2023-07-21 14:21 UTC, kadirovgm commented on tests/test_login_page.py
> +    assert "https://stellarburgers.nomoreparties.site/" == driver.current_url
Проверка теста должна находиться в ассерте, у тебя выполнение упадет на 42 строке, да, даже не дойдя до ассерта, в allure отчете ничего внятно не будет описано, поэтому я бы предложил через AND добавить проверку появления кнопки "оформить заказ". Сейчас выглядит не понятно, что ты в ассерте проверяешь наличие URL, который никак не говорит, что авторизация успешна.

2023-07-21 14:21 UTC, kadirovgm commented on locators.py
> +class TestLocators:
Примеры, на самом деле большинство, где есть завязывание на название классов, которые в коде могут легко меняться:

UNSELECTED_INGREDIENT_TABS = By.XPATH, '//*[contains(@class, "tab_tab") and not(contains(@class, "current"))]/child::span'

BUNS_HEADER = By.XPATH, \
        '//*[contains(@class, "text text_type_main-medium") and contains(text(), "Булки")]'

необходимо упросить локаторы, можно перечитать раздел нашего курса, стоит придерживаться правил: стабильности, уникальности, читабельности, краткости, лаконичности

2023-07-23 18:37 UTC, Zimbleik commented on locators.py
> +class TestLocators:
Попробовал поправить, там где исправил, вроде определяется так же однозначно

2023-07-23 21:02 UTC, kadirovgm approved these changes

2023-07-23 21:02 UTC, kadirovgm commented on locators.py
> +        '//h2[contains(text(), "Начинки")]'  # Заголовок начинок
супер!

2023-07-23 21:02 UTC, kadirovgm commented on conftest.py
> +    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=chrome_options)
можно лучше: должно сработать и без install

2023-07-23 21:02 UTC, kadirovgm commented on locators.py
> +        'html/body/div/div/main/section[contains(@class, "BurgerIngredients_ingredients")]/div/div[contains(@class, "current")]/child::span'  # Выбранная вкладка
можно лучше: эти два локатора все еще не кажутся стабильными, может по CSS селектору было бы оптимальнее?

2023-07-23 21:02 UTC, kadirovgm commented on tests/test_registration_page.py
> +    driver.find_element(*TestLocators.PERSONAL_ACCOUNT_BUTTON).click()
можно лучше: все же чтобы избегать повторений строки авторизации и регистрации нужно было вынести как отдельные функции

2023-08-22 11:06 UTC, merged